# Generated by Django 5.2.1 on 2025-06-03 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innerlyapp', '0003_alter_usuario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCriacao', models.DateField()),
                ('nivelHumor', models.SmallIntegerField()),
                ('anotacao', models.TextField()),
                ('dateString', models.CharField()),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innerlyapp.usuario')),
            ],
        ),
    ]
