# Generated by Django 5.2.1 on 2025-06-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innerlyapp', '0004_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='dateString',
            field=models.CharField(blank=True, null=True),
        ),
    ]
