# Generated by Django 5.2.1 on 2025-06-03 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innerlyapp', '0005_alter_registro_datestring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='dateString',
        ),
    ]
