# Generated by Django 5.2.1 on 2025-06-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innerlyapp', '0006_remove_registro_datestring'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='dataString',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
