# Generated by Django 5.2.1 on 2025-06-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innerlyapp', '0007_registro_datastring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='dataCriacao',
            field=models.DateField(unique=True),
        ),
    ]
