# Generated by Django 5.2.1 on 2025-06-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innerlyapp', '0008_alter_registro_datacriacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='dataCriacao',
            field=models.DateField(),
        ),
    ]
